import { env } from "./env.js";

const toBoolean = (value) => value === "true";

export const config = Object.freeze({
  env: env.NODE_ENV,
  port: env.PORT,
  database: env.DB_DATABASE,
  username: env.DB_USERNAME,
  password: env.DB_PASSWORD,
  host: env.DB_HOST,
  dialect: env.DB_DIALECT,
  dbPort: env.DB_PORT,
  appLocal: env.APP_LOCALE,
  appTimeZone: env.APP_TIMEZONE,
  jwtSecretKey: env.JWT_SECRET_KEY,
  jwtExpiration: env.JWT_EXPIRATION,
  jwtAlgorithm: env.JWT_ALGORITHM,
  jwtAudience: env.JWT_AUDIENCE,
  jwtIssuer: env.JWT_ISSUER,
  encryptSalt: Number(env.ENCRYP_SALT),
  dummyHash: env.DUMMY_HASH,
  defaultRole: env.DEFAULT_ROLE,
  basePath: env.BASE_PATH,
  jwtSecretKeyCam: env.JWT_SECRET_KEY_CAM,
  jwtExpirationCam: env.JWT_EXPIRATION_CAM,
  sqSyncAlter: toBoolean(env.SQ_SYNC_ALTER),
  sqSyncForce: toBoolean(env.SQ_SYNC_FORCE),
  dbSslRequire: toBoolean(env.DB_SSL_REQUIRE),
  dbSslUnauthorized: toBoolean(env.DB_SSL_UNAUTHIRIZED),
  mqttUrl: env.MQTT_URL,
  mqttUsername: env.MQTT_USERNAME,
  mqttPassword: env.MQTT_PASSWORD,
  mqttClientId: env.MQTT_CLIENT_ID,
  autoCreateScanConfig: toBoolean(env.AUTO_CREATE_SCAN_CONFIG),
  timeoutMqtt: env.TIMEOUT_MQTT,
});
